- name: Pull swag image
  docker_image:
    name: lscr.io/linuxserver/swag
    source: pull
    timeout: 300
  tags: web_server

- name: Init swag
  docker_container:
    name: swag
    image: lscr.io/linuxserver/swag
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      URL: "{{ domain_name }}"
      VALIDATION: duckdns
      SUBDOMAINS: wildcard
      EMAIL: "{{ email }}"
      DUCKDNSTOKEN: "{{ duckdns_token }}"
      ONLY_SUBDOMAINS: "true"
      DOCKER_MODS: linuxserver/mods:swag-dashboard
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/swag/config:/config
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ swag_subnet_ip }}"
  tags: web_server

- name: Wait until swag nginx directory exists
  wait_for:
    path: /etc/swag/config/nginx/
  tags: web_server

- name: Create nginx config to block external ips
  copy:
    dest: /etc/swag/config/nginx/internal.conf
    content: |
      allow {{ external_ip }};
      allow {{ subnet_ip }};
      allow 192.168.1.0/24;
      deny all;
  notify: Restart swag
  tags: web_server

- name: Create nginx config for cors
  copy:
    dest: /etc/swag/config/nginx/cors.conf
    content: |
      if ($request_method ~* "(GET|POST|HEAD)") {
        add_header "Access-Control-Allow-Origin"  *;
      }
  notify: Restart swag
  tags: web_server

- name: Enable swag dashboard upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/dashboard.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/dashboard.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: web_server

- name: Hide apps from search engines
  lineinfile:
    path: /etc/swag/config/nginx/ssl.conf
    insertafter: EOF
    line: add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
  notify: Restart swag
  tags: web_server
