# general
username: pi
puid: "1000"
guid: "1000"
timezone: Europe/Moscow
network_interface: wlan0
home_dir: /home/pi
data_dir: /mnt/data
internal_ip: 192.168.1.9

# docker
subnet_name: internal
subnet_ip: 172.20.0.0/16
subnet_gateway: 172.20.0.1
swag_subnet_ip: 172.20.0.2
cloudflared_subnet_ip: 172.20.0.3
pihole_subnet_ip: 172.20.0.4
qbittorrent_subnet_ip: 172.20.0.5
homer_subnet_ip: 172.20.0.6
lidarr_subnet_ip: 172.20.0.7
wireguard_subnet_ip: 172.20.0.8
vaultwarden_subnet_ip: 172.20.0.9
watchtower_subnet_ip: 172.20.0.10
radarr_subnet_ip: 172.20.0.11
jackett_subnet_ip: 172.20.0.12
sonarr_subnet_ip: 172.20.0.13
jellyfin_subnet_ip: 172.20.0.14
nextcloud_mariadb_subnet_ip: 172.20.0.15
nextcloud_subnet_ip: 172.20.0.16
navidrome_subnet_ip: 172.20.0.17
prowlarr_subnet_ip: 172.20.0.18
flaresolverr_subnet_ip: 172.20.0.19
photoprism_mariadb_subnet_ip: 172.20.0.20
photoprism_subnet_ip: 172.20.0.21
readarr_subnet_ip: 172.20.0.22

# vpn
wireguard_subnet: 10.13.13.0
wireguard_port: "51820"

# raspotify
librespot_bitrate: "320"
librespot_control_port: "4070"
librespot_zeroconf_port: "4071"
output_device: iec958:CARD=MQA,DEV=0

# mail
smtp_host: smtp.gmail.com
smtp_port: "587"

# tor
tor_proxy_port: "9050"
